use_frameworks!

platform :ios, '8.0'

target 'YDCategorySDK_Example' do
  pod 'YDCategorySDK', :path => '../'

  target 'YDCategorySDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
